# Generated by Django 6.0.4 on 2026-06-17 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_doctorreview'),
        ('patients', '0002_patientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('total_donations', models.IntegerField(default=0)),
                ('is_eligible', models.BooleanField(default=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=20, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('component_type', models.CharField(choices=[('WHOLE_BLOOD', 'Whole Blood'), ('PACKED_RBC', 'Packed RBC'), ('PLATELETS', 'Platelets'), ('FRESH_FROZEN_PLASMA', 'Fresh Frozen Plasma'), ('CRYOPRECIPITATE', 'Cryoprecipitate')], max_length=25)),
                ('units_required', models.IntegerField()),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CROSS_MATCHED', 'Cross Matched'), ('ISSUED', 'Issued'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('reason', models.TextField()),
                ('required_date', models.DateField()),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('component_type', models.CharField(choices=[('WHOLE_BLOOD', 'Whole Blood'), ('PACKED_RBC', 'Packed RBC'), ('PLATELETS', 'Platelets'), ('FRESH_FROZEN_PLASMA', 'Fresh Frozen Plasma'), ('CRYOPRECIPITATE', 'Cryoprecipitate')], max_length=25)),
                ('collection_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('volume_ml', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('ISSUED', 'Issued'), ('EXPIRED', 'Expired'), ('DISCARDED', 'Discarded'), ('TESTING', 'Testing')], default='TESTING', max_length=15)),
                ('storage_location', models.CharField(max_length=50)),
                ('tested_by', models.CharField(blank=True, max_length=200)),
                ('is_tested', models.BooleanField(default=False)),
                ('test_results', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='blood_bank.blooddonor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrossMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('COMPATIBLE', 'Compatible'), ('INCOMPATIBLE', 'Incompatible'), ('PENDING', 'Pending')], default='PENDING', max_length=15)),
                ('tested_by', models.CharField(max_length=200)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_matches', to='blood_bank.bloodrequest')),
                ('blood_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_bank.bloodunit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
    ]
