# Generated by Django 6.0.4 on 2026-06-17 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment_check_in_time_appointment_check_out_time_and_more'),
        ('departments', '0001_initial'),
        ('doctors', '0002_doctorreview'),
        ('patients', '0002_patientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('current_token', models.CharField(blank=True, max_length=20)),
                ('next_tokens', models.TextField(blank=True)),
                ('avg_wait_time_minutes', models.IntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_displays', to='departments.department')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_displays', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Queue Display',
                'verbose_name_plural': 'Queue Displays',
                'ordering': ['department', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.CharField(max_length=20)),
                ('queue_type', models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('WALK_IN', 'Walk In'), ('FOLLOW_UP', 'Follow Up'), ('EMERGENCY', 'Emergency')], max_length=15)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_CONSULTATION', 'In Consultation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('SKIPPED', 'Skipped')], default='WAITING', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=10)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('called_time', models.DateTimeField(blank=True, null=True)),
                ('consultation_start', models.DateTimeField(blank=True, null=True)),
                ('consultation_end', models.DateTimeField(blank=True, null=True)),
                ('estimated_wait_minutes', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entry', to='appointments.appointment')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='departments.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Queue Entry',
                'verbose_name_plural': 'Queue Entries',
                'ordering': ['priority', 'check_in_time'],
            },
        ),
    ]
