# Generated by Django 6.0.6 on 2026-06-20 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='da',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='esi_employee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Employee ESI (0.75%)', max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='esi_employer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Employer ESI (3.25%)', max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='food_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='leaves_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='loan_emi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='lop_days',
            field=models.PositiveIntegerField(default=0, help_text='Loss of Pay days'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='other_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_method',
            field=models.CharField(blank=True, default='BANK_TRANSFER', max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pf_employee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Employee PF (12% of basic)', max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pf_employer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Employer PF (12% of basic)', max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='present_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax Deducted at Source', max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payroll',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='working_days',
            field=models.PositiveIntegerField(default=26),
        ),
        migrations.CreateModel(
            name='SalaryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('previous_basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('increment_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_revisions', to='staff.staffmember')),
            ],
            options={
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text='Monthly basic pay', max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0, help_text='House Rent Allowance', max_digits=12)),
                ('da', models.DecimalField(decimal_places=2, default=0, help_text='Dearness Allowance', max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('food_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employer_pf', models.DecimalField(decimal_places=2, default=0, help_text='Employer PF (12% of basic)', max_digits=12)),
                ('employer_esi', models.DecimalField(decimal_places=2, default=0, help_text='Employer ESI (3.25% of gross)', max_digits=12)),
                ('pf_deduction', models.BooleanField(default=True, help_text='Deduct PF from employee (12% of basic)')),
                ('esi_deduction', models.BooleanField(default=True, help_text='Deduct ESI from employee (0.75% of gross)')),
                ('professional_tax', models.BooleanField(default=True, help_text='Deduct professional tax')),
                ('tds_percentage', models.DecimalField(decimal_places=2, default=0, help_text='TDS percentage on salary', max_digits=5)),
                ('loan_emi', models.DecimalField(decimal_places=2, default=0, help_text='Monthly loan EMI deduction', max_digits=12)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effective_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='staff.staffmember')),
            ],
        ),
        migrations.CreateModel(
            name='StaffLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=20, unique=True)),
                ('loan_type', models.CharField(max_length=50)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('emi_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_installments', models.PositiveIntegerField()),
                ('paid_installments', models.PositiveIntegerField(default=0)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disbursement_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DEFAULTED', 'Defaulted')], default='ACTIVE', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='staff.staffmember')),
            ],
            options={
                'ordering': ['-disbursement_date'],
            },
        ),
    ]
