# Generated by Django 6.0.6 on 2026-06-21 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('staff', '0002_payroll_bonus_payroll_da_payroll_esi_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_shift', models.CharField(choices=[('MORNING', 'Morning (6AM-2PM)'), ('AFTERNOON', 'Afternoon (2PM-10PM)'), ('NIGHT', 'Night (10PM-6AM)'), ('GENERAL', 'General (9AM-5PM)'), ('ROTATING', 'Rotating')], max_length=15)),
                ('to_shift', models.CharField(choices=[('MORNING', 'Morning (6AM-2PM)'), ('AFTERNOON', 'Afternoon (2PM-10PM)'), ('NIGHT', 'Night (10PM-6AM)'), ('GENERAL', 'General (9AM-5PM)'), ('ROTATING', 'Rotating')], max_length=15)),
                ('date', models.DateField()),
                ('patient_updates', models.TextField(blank=True, help_text='Critical patient updates')),
                ('pending_tasks', models.TextField(blank=True, help_text='Tasks to be completed')),
                ('medications_due', models.TextField(blank=True, help_text='Upcoming medication schedules')),
                ('equipment_issues', models.TextField(blank=True, help_text='Equipment problems')),
                ('incidents', models.TextField(blank=True, help_text='Incidents or concerns')),
                ('general_notes', models.TextField(blank=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
                ('from_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_given', to='staff.staffmember')),
                ('to_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handovers_received', to='staff.staffmember')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
