# Generated by Django 6.0.4 on 2026-06-17 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment_check_in_time_appointment_check_out_time_and_more'),
        ('doctors', '0002_doctorreview'),
        ('patients', '0002_patientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('discharge_type', models.CharField(choices=[('NORMAL', 'Normal'), ('AGAINST_MEDICAL_ADVICE', 'Against Medical Advice'), ('TRANSFERRED', 'Transferred'), ('EXPIRED', 'Expired'), ('ABSCONDED', 'Absconded')], default='NORMAL', max_length=30)),
                ('admission_diagnosis', models.TextField()),
                ('discharge_diagnosis', models.TextField()),
                ('procedures_performed', models.TextField(blank=True)),
                ('treatment_given', models.TextField()),
                ('condition_at_discharge', models.TextField()),
                ('medications_on_discharge', models.TextField(blank=True)),
                ('dietary_instructions', models.TextField(blank=True)),
                ('activity_restrictions', models.TextField(blank=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('emergency_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summaries', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summaries', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Discharge Summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('follow_up_type', models.CharField(choices=[('POST_SURGERY', 'Post Surgery'), ('POST_DISCHARGE', 'Post Discharge'), ('ROUTINE', 'Routine'), ('LAB_REVIEW', 'Lab Review'), ('IMAGING_REVIEW', 'Imaging Review'), ('MEDICATION_REVIEW', 'Medication Review')], max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', max_length=20)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discharge_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='discharge.dischargesummary')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='patients.patient')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Readmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readmission_date', models.DateField()),
                ('reason', models.TextField()),
                ('is_related_to_original', models.BooleanField(default=False)),
                ('days_since_discharge', models.IntegerField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_discharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readmissions', to='discharge.dischargesummary')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readmissions', to='patients.patient')),
            ],
            options={
                'ordering': ['-readmission_date'],
            },
        ),
    ]
