# Generated by Django 6.0.4 on 2026-06-17 01:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_doctorreview'),
        ('patients', '0002_patientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTheater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('floor', models.CharField(max_length=10)),
                ('theater_type', models.CharField(choices=[('MAJOR', 'Major'), ('MINOR', 'Minor'), ('CARDIAC', 'Cardiac'), ('NEURO', 'Neuro'), ('ORTHOPEDIC', 'Orthopedic'), ('OPHTHALMIC', 'Ophthalmic'), ('EMERGENCY', 'Emergency')], max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=20)),
                ('equipment_list', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_number', models.CharField(max_length=20, unique=True)),
                ('surgery_type', models.CharField(choices=[('ELECTIVE', 'Elective'), ('EMERGENCY', 'Emergency'), ('DAY_CASE', 'Day Case')], max_length=20)),
                ('procedure_name', models.CharField(max_length=300)),
                ('diagnosis', models.TextField()),
                ('scheduled_date', models.DateTimeField()),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed')], default='SCHEDULED', max_length=20)),
                ('anesthesia_type', models.CharField(choices=[('GENERAL', 'General'), ('SPINAL', 'Spinal'), ('EPIDURAL', 'Epidural'), ('LOCAL', 'Local'), ('REGIONAL', 'Regional'), ('SEDATION', 'Sedation')], max_length=20)),
                ('pre_op_diagnosis', models.TextField(blank=True)),
                ('post_op_diagnosis', models.TextField(blank=True)),
                ('procedure_notes', models.TextField(blank=True)),
                ('complications', models.TextField(blank=True)),
                ('estimated_duration', models.IntegerField(help_text='Duration in minutes')),
                ('actual_duration', models.IntegerField(blank=True, null=True)),
                ('blood_loss_ml', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='operation_theater.operationtheater')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='patients.patient')),
                ('primary_surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries_as_primary', to='doctors.doctor')),
            ],
            options={
                'verbose_name_plural': 'surgeries',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='PreOpChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_identity_confirmed', models.BooleanField(default=False)),
                ('consent_signed', models.BooleanField(default=False)),
                ('site_marked', models.BooleanField(default=False)),
                ('allergies_checked', models.BooleanField(default=False)),
                ('blood_type_confirmed', models.BooleanField(default=False)),
                ('blood_units_available', models.BooleanField(default=False)),
                ('npo_status_confirmed', models.BooleanField(default=False)),
                ('pre_op_medications_given', models.BooleanField(default=False)),
                ('imaging_available', models.BooleanField(default=False)),
                ('lab_results_reviewed', models.BooleanField(default=False)),
                ('anesthesia_assessment_done', models.BooleanField(default=False)),
                ('equipment_checked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.CharField(max_length=200)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_op_checklist', to='operation_theater.surgery')),
            ],
            options={
                'verbose_name': 'Pre-Op Checklist',
                'verbose_name_plural': 'Pre-Op Checklists',
            },
        ),
        migrations.CreateModel(
            name='PostOpNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_status', models.CharField(choices=[('STABLE', 'Stable'), ('GUARDED', 'Guarded'), ('CRITICAL', 'Critical'), ('GOOD', 'Good')], max_length=20)),
                ('pain_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('vitals_stable', models.BooleanField(default=True)),
                ('consciousness_level', models.CharField(choices=[('ALERT', 'Alert'), ('DROWSY', 'Drowsy'), ('RESPONSIVE_TO_PAIN', 'Responsive to Pain'), ('UNRESPONSIVE', 'Unresponsive')], max_length=30)),
                ('instructions', models.TextField()),
                ('diet_instructions', models.TextField(blank=True)),
                ('activity_restrictions', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('complications', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_op_note', to='operation_theater.surgery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurgicalTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SURGEON', 'Surgeon'), ('ASSISTANT_SURGEON', 'Assistant Surgeon'), ('ANESTHESIOLOGIST', 'Anesthesiologist'), ('SCRUB_NURSE', 'Scrub Nurse'), ('CIRCULATING_NURSE', 'Circulating Nurse'), ('TECHNICIAN', 'Technician')], max_length=30)),
                ('member_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='operation_theater.surgery')),
            ],
            options={
                'ordering': ['surgery', 'role'],
            },
        ),
    ]
