# Generated by Django 6.0.4 on 2026-06-17 01:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('doctors', '0002_doctorreview'),
        ('patients', '0002_patientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('ambulance_type', models.CharField(choices=[('BASIC', 'Basic'), ('ADVANCED', 'Advanced'), ('NEONATAL', 'Neonatal'), ('CARDIAC', 'Cardiac')], max_length=15)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=15)),
                ('paramedic_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_CALL', 'On Call'), ('EN_ROUTE', 'En Route'), ('AT_SCENE', 'At Scene'), ('RETURNING', 'Returning'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=15)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('ON_CALL_DOCTOR', 'On-Call Doctor'), ('SURGEON', 'Surgeon'), ('ANESTHESIOLOGIST', 'Anesthesiologist'), ('BLOOD_BANK', 'Blood Bank'), ('POLICE', 'Police'), ('FIRE', 'Fire Department'), ('POISON_CONTROL', 'Poison Control')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('triage_level', models.IntegerField(choices=[(1, 'Resuscitation'), (2, 'Emergent'), (3, 'Urgent'), (4, 'Less Urgent'), (5, 'Non-Urgent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('chief_complaint', models.TextField()),
                ('arrival_mode', models.CharField(choices=[('AMBULANCE', 'Ambulance'), ('WALK_IN', 'Walk-In'), ('POLICE', 'Police'), ('REFERRED', 'Referred'), ('OTHER', 'Other')], max_length=15)),
                ('arrival_time', models.DateTimeField()),
                ('triage_time', models.DateTimeField(blank=True, null=True)),
                ('treatment_start_time', models.DateTimeField(blank=True, null=True)),
                ('discharge_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('TRIAGED', 'Triaged'), ('IN_TREATMENT', 'In Treatment'), ('ADMITTED', 'Admitted'), ('DISCHARGED', 'Discharged'), ('TRANSFERRED', 'Transferred'), ('DECEASED', 'Deceased'), ('LEFT_AMA', 'Left Against Medical Advice')], default='WAITING', max_length=15)),
                ('vitals_on_arrival', models.TextField(blank=True)),
                ('disposition', models.CharField(blank=True, choices=[('DISCHARGED', 'Discharged'), ('ADMITTED', 'Admitted'), ('TRANSFERRED', 'Transferred'), ('DECEASED', 'Deceased'), ('LEFT_AMA', 'Left Against Medical Advice'), ('OBSERVATION', 'Observation')], max_length=15)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_notes', models.TextField(blank=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_visits', to='departments.bed')),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_visits', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-arrival_time'],
            },
        ),
        migrations.CreateModel(
            name='AmbulanceDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_time', models.DateTimeField()),
                ('arrival_at_scene', models.DateTimeField(blank=True, null=True)),
                ('departure_from_scene', models.DateTimeField(blank=True, null=True)),
                ('arrival_at_hospital', models.DateTimeField(blank=True, null=True)),
                ('pickup_location', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DISPATCHED', 'Dispatched'), ('AT_SCENE', 'At Scene'), ('EN_ROUTE_HOSPITAL', 'En Route to Hospital'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DISPATCHED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='emergency.ambulance')),
                ('emergency_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_dispatch', to='emergency.emergencyvisit')),
            ],
            options={
                'ordering': ['-dispatch_time'],
            },
        ),
    ]
