# Generated by Django 6.0.6 on 2026-06-21 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorreview'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_a', models.CharField(db_index=True, max_length=200)),
                ('drug_b', models.CharField(db_index=True, max_length=200)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CONTRAINDICATED', 'Contraindicated')], max_length=20)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['drug_a', 'drug_b'],
                'unique_together': {('drug_a', 'drug_b')},
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('diagnosis', models.CharField(max_length=300)),
                ('is_global', models.BooleanField(default=False, help_text='Available to all doctors')),
                ('items', models.JSONField(default=list, help_text='[{medicine_name, dosage, frequency, duration, instructions}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_templates', to='doctors.doctor')),
            ],
        ),
    ]
