# Generated by Django 6.0.6 on 2026-06-21 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_check_in_time_appointment_check_out_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fee_receipt_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fees_paid',
            field=models.BooleanField(default=False, help_text='Consulting fees have been paid'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lab_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lab_results_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription_uploaded',
            field=models.BooleanField(default=False, help_text='Doctor has uploaded prescription'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, help_text="Patient's symptoms or health problem"),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vitals_recorded',
            field=models.BooleanField(default=False, help_text='Staff has recorded BP, height, weight'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked In'), ('VITALS_RECORDED', 'Vitals Recorded'), ('FEES_PAID', 'Fees Paid'), ('READY', 'Ready for Consultation'), ('IN_CONSULTATION', 'In Consultation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20),
        ),
    ]
