# Generated by Django 6.0.6 on 2026-06-21 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_checked_in_by_appointment_fee_amount_and_more'),
        ('doctors', '0002_doctorreview'),
        ('patients', '0003_patient_photo_patient_photo_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(help_text='0-10 NPS score')),
                ('doctor_rating', models.IntegerField(default=0, help_text='Doctor consultation quality 1-5')),
                ('staff_rating', models.IntegerField(default=0, help_text='Staff behavior 1-5')),
                ('cleanliness_rating', models.IntegerField(default=0, help_text='Hospital cleanliness 1-5')),
                ('wait_time_rating', models.IntegerField(default=0, help_text='Wait time satisfaction 1-5')),
                ('billing_rating', models.IntegerField(default=0, help_text='Billing transparency 1-5')),
                ('liked', models.TextField(blank=True, help_text='What did you like?')),
                ('improvement', models.TextField(blank=True, help_text='What can be improved?')),
                ('recommend', models.BooleanField(default=True, help_text='Would you recommend this hospital?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
