# Generated by Django 6.0.6 on 2026-06-21 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_patientfeedback'),
        ('patients', '0004_familygroup_familymember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('GENERAL', 'General Treatment Consent'), ('SURGERY', 'Surgical Consent'), ('ANESTHESIA', 'Anesthesia Consent'), ('BLOOD_TRANSFUSION', 'Blood Transfusion Consent'), ('IMAGING', 'Radiology/Imaging Consent'), ('PROCEDURE', 'Procedure Consent'), ('DISCHARGE_AMA', 'Discharge Against Medical Advice'), ('COVID_SCREENING', 'COVID Screening Consent')], max_length=30)),
                ('description', models.TextField()),
                ('risks_explained', models.TextField(blank=True)),
                ('patient_signature', models.TextField(blank=True, help_text='Base64 encoded signature image')),
                ('witness_name', models.CharField(blank=True, max_length=100)),
                ('witness_signature', models.TextField(blank=True)),
                ('consented', models.BooleanField(default=False)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_forms', to='appointments.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_forms', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
