# Generated by Django 6.0.4 on 2026-06-17 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment_check_in_time_appointment_check_out_time_and_more'),
        ('doctors', '0002_doctorreview'),
        ('patients', '0002_patientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=200)),
                ('allergy_type', models.CharField(choices=[('DRUG', 'Drug'), ('FOOD', 'Food'), ('ENVIRONMENTAL', 'Environmental'), ('LATEX', 'Latex'), ('OTHER', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('LIFE_THREATENING', 'Life Threatening')], max_length=20)),
                ('reaction', models.TextField()),
                ('first_observed', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergy_records', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Allergies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('SOAP', 'SOAP Note'), ('PROGRESS', 'Progress Note'), ('ADMISSION', 'Admission Note'), ('DISCHARGE', 'Discharge Note'), ('CONSULTATION', 'Consultation Note'), ('OPERATIVE', 'Operative Note'), ('OTHER', 'Other')], max_length=20)),
                ('subjective', models.TextField(blank=True, help_text="Patient's complaints", null=True)),
                ('objective', models.TextField(blank=True, help_text='Examination findings', null=True)),
                ('assessment', models.TextField(blank=True, help_text='Diagnosis/assessment', null=True)),
                ('plan', models.TextField(blank=True, help_text='Treatment plan', null=True)),
                ('content', models.TextField(blank=True, help_text='For non-SOAP notes', null=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('diagnosis', models.TextField()),
                ('goals', models.TextField()),
                ('interventions', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Temperature in Fahrenheit', max_digits=4, null=True)),
                ('blood_pressure_systolic', models.IntegerField(null=True)),
                ('blood_pressure_diastolic', models.IntegerField(null=True)),
                ('pulse_rate', models.IntegerField(help_text='Beats per minute', null=True)),
                ('respiratory_rate', models.IntegerField(help_text='Breaths per minute', null=True)),
                ('oxygen_saturation', models.DecimalField(decimal_places=1, help_text='SpO2 percentage', max_digits=4, null=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, help_text='Auto-calculated BMI', max_digits=4, null=True)),
                ('blood_sugar', models.DecimalField(decimal_places=2, help_text='Blood sugar in mg/dL', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to='doctors.doctor')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
