# Generated by Django 6.0.6 on 2026-06-21 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorreview'),
        ('patients', '0004_familygroup_familymember'),
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalsAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vital_name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('message', models.CharField(max_length=200)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals_alerts', to='patients.patient')),
                ('vital_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vitals.vitalsign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
