# Generated by Django 6.0.4 on 2026-06-17 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment_check_in_time_appointment_check_out_time_and_more'),
        ('doctors', '0002_doctorreview'),
        ('patients', '0002_patientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preparation_instructions', models.TextField(blank=True)),
                ('turnaround_time', models.CharField(max_length=50)),
                ('requires_contrast', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImagingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('body_part', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'Stat')], default='ROUTINE', max_length=10)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('clinical_indication', models.TextField()),
                ('special_instructions', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_orders', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_orders', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_orders', to='patients.patient')),
                ('imaging_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='radiology.imagingtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField()),
                ('impression', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('reported_by', models.CharField(max_length=200)),
                ('verified_by', models.CharField(blank=True, max_length=200)),
                ('severity', models.CharField(choices=[('NORMAL', 'Normal'), ('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='radiology_reports/')),
                ('images', models.FileField(blank=True, null=True, upload_to='radiology_images/')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('imaging_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='radiology.imagingorder')),
            ],
        ),
    ]
