# Generated by Django 6.0.4 on 2026-06-10 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INSURANCE_CARD', 'Insurance Card'), ('ID_PROOF', 'ID Proof'), ('LAB_REPORT', 'Lab Report'), ('PRESCRIPTION', 'Prescription'), ('IMAGING', 'Imaging'), ('DISCHARGE_SUMMARY', 'Discharge Summary'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='patient_documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
