# Generated by Django 6.0.6 on 2026-06-21 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo_confirmed',
            field=models.BooleanField(default=False, help_text='Photo confirmed by staff, cannot be changed by patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_photos_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
