# Generated by Django 6.0.6 on 2026-06-21 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_photo_patient_photo_confirmed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Sharma Family'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_user', models.ForeignKey(help_text='The main account holder', on_delete=django.db.models.deletion.CASCADE, related_name='family_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('SELF', 'Self'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('family_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='patients.familygroup')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links', to='patients.patient')),
            ],
            options={
                'ordering': ['-is_primary', 'relationship'],
                'unique_together': {('family_group', 'patient')},
            },
        ),
    ]
