# Generated by Django 6.0.6 on 2026-06-20 18:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_invoice_cgst_amount_invoice_gst_percentage_and_more'),
        ('departments', '0001_initial'),
        ('inventory', '0002_goodsreceivednote_grnitem_vendorpayment'),
        ('patients', '0002_patientdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tax_type', models.CharField(choices=[('CGST', 'CGST'), ('SGST', 'SGST'), ('IGST', 'IGST'), ('TDS', 'TDS'), ('PROFESSIONAL_TAX', 'Professional Tax')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['tax_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('group_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=20)),
                ('nature', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.accountgroup')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accountgroup')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DailyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('cash_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('card_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('upi_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_banking_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('insurance_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_invoices', models.PositiveIntegerField(default=0)),
                ('total_refunds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reconciled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period_number', models.PositiveIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.fiscalyear')),
            ],
            options={
                'ordering': ['fiscal_year', 'period_number'],
                'unique_together': {('fiscal_year', 'period_number')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('INVOICE', 'Patient Invoice'), ('PAYMENT', 'Payment Receipt'), ('PAYROLL', 'Payroll'), ('PURCHASE', 'Purchase Order'), ('EXPENSE', 'Expense'), ('ADJUSTMENT', 'Adjustment'), ('OPENING', 'Opening Balance'), ('CLOSING', 'Closing Entry')], default='MANUAL', max_length=20)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.fiscalperiod')),
            ],
            options={
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('SALARY', 'Salaries & Wages'), ('MEDICAL_SUPPLIES', 'Medical Supplies'), ('MEDICINE', 'Medicines & Drugs'), ('EQUIPMENT', 'Equipment & Instruments'), ('MAINTENANCE', 'Maintenance & Repairs'), ('UTILITIES', 'Utilities (Electricity, Water, Gas)'), ('RENT', 'Rent & Lease'), ('INSURANCE', 'Insurance'), ('MARKETING', 'Marketing & Advertising'), ('IT', 'IT & Software'), ('FOOD', 'Food & Catering'), ('LAUNDRY', 'Laundry & Housekeeping'), ('TRANSPORT', 'Transport & Ambulance'), ('LEGAL', 'Legal & Professional'), ('TRAINING', 'Training & Development'), ('MISCELLANEOUS', 'Miscellaneous')], max_length=30)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('receipt_file', models.FileField(blank=True, upload_to='expense_receipts/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='departments.department')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_submitted', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='inventory.vendor')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PatientAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_number', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='CASH', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('is_refunded', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_against_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_adjustments', to='billing.invoice')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_advances', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='accounting.journalentry')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounting.account')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='departments.department')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounting.fiscalyear')),
            ],
            options={
                'ordering': ['department', 'account'],
                'unique_together': {('fiscal_year', 'department', 'account')},
            },
        ),
    ]
